# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macOS-latest, windows-latest]
        jdk: [ 11, 17 ]  # (open)JDK releases
        exclude:  # to save time and resources
          - os: windows-latest
            version: 11
          - os: macOS-latest
            version: 11

    steps:
    - uses: actions/checkout@v3
    - name: Set up openJDK version
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'zulu'  # =openJDK
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build and Test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Do one Coveralls test report
      uses: gradle/gradle-build-action@v2
      if: matrix.os == 'ubuntu-latest' && matrix.jdk == 17
      with:
        arguments:  jacocoTestReport coveralls
